import type { SkillKey, SkillLevel } from "./learning-model.ts";

export type VisualData =
  | { kind: "array"; rows: number; columns: number; fadedRows?: number }
  | { kind: "base-ten"; left: number; right: number }
  | { kind: "fraction"; total: number; denominator: number; numerator: number }
  | { kind: "number-line"; start: number; subtract: number };

export type Mission = {
  id: string;
  eyebrow: string;
  title: string;
  story: string;
  prompt: string;
  equation: string;
  options: number[];
  answer: number;
  skill: SkillKey;
  skillLabel: string;
  level: SkillLevel;
  levelLabel: "Build" | "Connect" | "Transfer";
  visual: VisualData;
  insightByAnswer: Record<number, string>;
  defaultInsight: string;
  learnerRead: string;
  whyThisChallenge: string;
  nudge: string;
  nextMove: string;
  nextMoveWhy: string;
  scaffold: {
    prompt: string;
    equation: string;
    options: number[];
    answer: number;
    coach: string;
    wrongFeedback: string;
    visual: VisualData;
  };
  celebration: string;
};

export const MISSIONS: Mission[] = [
  {
    id: "solar-array-connect",
    eyebrow: "Mission 04 · Solar Array",
    title: "Wake the west wing",
    story: "Six solar rows must power the habitat before lunar night.",
    prompt: "The array has 6 rows of 4 cells. How many cells are working?",
    equation: "6 × 4 = ?",
    options: [10, 20, 24, 28],
    answer: 24,
    skill: "arrays",
    skillLabel: "Equal groups",
    level: 2,
    levelLabel: "Connect",
    visual: { kind: "array", rows: 6, columns: 4 },
    insightByAnswer: {
      10: "You added the two factors instead of making equal groups.",
      20: "You counted five rows and dropped the final group of four.",
      28: "You counted one extra group of four.",
    },
    defaultInsight: "The groups are visible, but the total is not stable yet.",
    learnerRead: "Nova recognizes equal groups when an array is visible and is learning to translate every row into multiplication.",
    whyThisChallenge: "A structured array connects Nova’s reliable skip-counting to multiplication.",
    nudge: "Let’s shrink the array, touch every row, then come right back.",
    nextMove: "Keep the array for one more challenge, then fade two rows and ask Nova to reconstruct the missing groups.",
    nextMoveWhy: "Strengthens equal-group structure",
    scaffold: {
      prompt: "Build 3 rows of 4 cells. How many cells altogether?",
      equation: "4 + 4 + 4 = ?",
      options: [7, 12, 16],
      answer: 12,
      coach: "Each row is one equal group. Count all three groups: 4, 8, 12.",
      wrongFeedback: "Touch each of the three rows once and add 4 + 4 + 4.",
      visual: { kind: "array", rows: 3, columns: 4 },
    },
    celebration: "All six rows are online. You connected an array to repeated addition.",
  },
  {
    id: "cargo-bay-connect",
    eyebrow: "Mission 05 · Cargo Bay",
    title: "Balance the supply lift",
    story: "Two cargo crews are combining oxygen canisters for the climb.",
    prompt: "One crew loaded 27 canisters and another loaded 36. How many total?",
    equation: "27 + 36 = ?",
    options: [53, 63, 73, 613],
    answer: 63,
    skill: "placeValue",
    skillLabel: "Place value",
    level: 2,
    levelLabel: "Connect",
    visual: { kind: "base-ten", left: 27, right: 36 },
    insightByAnswer: {
      53: "You combined the ones, but the regrouped ten did not reach the tens column.",
      73: "An extra ten slipped into the total.",
      613: "You joined digits instead of combining their place values.",
    },
    defaultInsight: "The ones need to be regrouped before the tens are combined.",
    learnerRead: "Nova combines tens and ones reliably until a sum creates a new ten that must move columns.",
    whyThisChallenge: "Base-ten blocks make the regrouped ten visible before Nova returns to notation.",
    nudge: "Let’s pack 13 ones into one ten and three ones.",
    nextMove: "Build one more regrouping problem with base-ten blocks, then replace the blocks with a written tens-and-ones record.",
    nextMoveWhy: "Connects concrete regrouping to notation",
    scaffold: {
      prompt: "Seven ones plus six ones makes 13. How many tens do we regroup?",
      equation: "7 ones + 6 ones = 1 ten + 3 ones",
      options: [0, 1, 13],
      answer: 1,
      coach: "Ten of the ones snap together into one new ten. Three ones remain.",
      wrongFeedback: "Make a bundle of ten from the 13 ones. Count how many complete tens that creates.",
      visual: { kind: "base-ten", left: 7, right: 6 },
    },
    celebration: "Lift balanced. You regrouped across place values without losing a ten.",
  },
  {
    id: "water-vault-connect",
    eyebrow: "Mission 06 · Water Vault",
    title: "Share the moonwater",
    story: "Three of the four greenhouse pods need an equal water ration.",
    prompt: "The tank holds 12 liters. What is 3/4 of the tank?",
    equation: "¾ of 12 = ?",
    options: [3, 4, 8, 9],
    answer: 9,
    skill: "fractions",
    skillLabel: "Fractions of sets",
    level: 2,
    levelLabel: "Connect",
    visual: { kind: "fraction", total: 12, denominator: 4, numerator: 3 },
    insightByAnswer: {
      3: "You found one fourth, but the mission needs three fourths.",
      4: "You used the denominator as the answer instead of making four equal groups.",
      8: "You filled two groups instead of three.",
    },
    defaultInsight: "The set must be split into four equal groups before taking three.",
    learnerRead: "Nova can find a unit fraction of a set and is learning to combine the requested number of equal groups.",
    whyThisChallenge: "Equal water groups connect the denominator, unit fraction, and requested numerator.",
    nudge: "First find one fourth. Then take that amount three times.",
    nextMove: "Partition a new set into four equal groups, then compare one fourth with three fourths before removing the visual dividers.",
    nextMoveWhy: "Separates numerator and denominator roles",
    scaffold: {
      prompt: "If 12 liters split into 4 equal groups, how many liters are in one group?",
      equation: "12 ÷ 4 = ?",
      options: [3, 4, 6],
      answer: 3,
      coach: "One fourth is 3 liters. Three fourths is three groups of 3.",
      wrongFeedback: "Share all 12 liters equally across four groups, then count the liters in just one group.",
      visual: { kind: "fraction", total: 12, denominator: 4, numerator: 1 },
    },
    celebration: "The greenhouse is hydrated. You found a fraction by making equal groups.",
  },
  {
    id: "return-route-connect",
    eyebrow: "Mission 07 · Return Route",
    title: "Plot the rover home",
    story: "The rover is 52 marks out. Its return route covers 28 marks.",
    prompt: "Where will the rover be after traveling back 28 marks from 52?",
    equation: "52 − 28 = ?",
    options: [24, 26, 34, 80],
    answer: 24,
    skill: "subtraction",
    skillLabel: "Subtraction across ten",
    level: 2,
    levelLabel: "Connect",
    visual: { kind: "number-line", start: 52, subtract: 28 },
    insightByAnswer: {
      26: "You subtracted the ones without crossing back through the ten.",
      34: "You took away 18 rather than 28.",
      80: "You combined the distances instead of finding what remains.",
    },
    defaultInsight: "Crossing the ten is easier when the jump is split into 20 and 8.",
    learnerRead: "Nova subtracts whole tens reliably and is learning to decompose a two-digit jump across a ten.",
    whyThisChallenge: "A number line exposes the intermediate landing point in a subtraction-across-ten strategy.",
    nudge: "Take one clean jump of 20 first. Then hop back 8.",
    nextMove: "Keep the intermediate landing point visible for one more problem, then hide it and ask Nova to name the two jumps.",
    nextMoveWhy: "Builds a reusable decomposition strategy",
    scaffold: {
      prompt: "Start at 52 and jump back 20. Where do you land?",
      equation: "52 − 20 = ?",
      options: [22, 32, 48],
      answer: 32,
      coach: "Subtracting two tens changes only the tens digit: 52 becomes 32.",
      wrongFeedback: "Jump back two whole tens from 52. The ones digit stays 2 while the tens digit changes.",
      visual: { kind: "number-line", start: 52, subtract: 20 },
    },
    celebration: "Rover recovered. You decomposed a hard jump into two friendly jumps.",
  },
  {
    id: "antenna-build",
    eyebrow: "Mission 08 · Antenna Grid",
    title: "Tune the signal tiles",
    story: "Four antenna rows each need three signal tiles.",
    prompt: "There are 4 equal rows of 3 tiles. How many tiles are there?",
    equation: "3 + 3 + 3 + 3 = ?",
    options: [7, 9, 12, 16],
    answer: 12,
    skill: "arrays",
    skillLabel: "Equal groups",
    level: 1,
    levelLabel: "Build",
    visual: { kind: "array", rows: 4, columns: 3 },
    insightByAnswer: {
      7: "You added the number of rows and the number in each row.",
      9: "You counted only three of the four rows.",
      16: "You used four in every row instead of three.",
    },
    defaultInsight: "Counting each equal row once will keep the total stable.",
    learnerRead: "Nova benefits from touching and counting each equal group before naming the total.",
    whyThisChallenge: "Every cell stays visible so Nova can coordinate rows, groups, and repeated addition.",
    nudge: "Start with just two rows. Count three, then three more.",
    nextMove: "Build one more array, then connect its repeated addition to a multiplication sentence.",
    nextMoveWhy: "Establishes the equal-group unit",
    scaffold: {
      prompt: "Two rows hold 3 tiles each. How many tiles?",
      equation: "3 + 3 = ?",
      options: [5, 6, 9],
      answer: 6,
      coach: "Touch each row once: one group of 3, then another group of 3.",
      wrongFeedback: "Count all three tiles in the first row, then all three in the second row.",
      visual: { kind: "array", rows: 2, columns: 3 },
    },
    celebration: "Signal locked. You counted every equal group exactly once.",
  },
  {
    id: "greenhouse-build",
    eyebrow: "Mission 09 · Greenhouse",
    title: "Count the seed packs",
    story: "Two trays hold seed packs sorted into tens and ones.",
    prompt: "Combine 24 seed packs and 15 seed packs. How many altogether?",
    equation: "24 + 15 = ?",
    options: [29, 39, 49, 2415],
    answer: 39,
    skill: "placeValue",
    skillLabel: "Place value",
    level: 1,
    levelLabel: "Build",
    visual: { kind: "base-ten", left: 24, right: 15 },
    insightByAnswer: {
      29: "You combined the ones but kept only one group of tens.",
      49: "One extra ten entered the total.",
      2415: "You joined the numerals instead of combining tens and ones.",
    },
    defaultInsight: "Combine tens with tens and ones with ones.",
    learnerRead: "Nova is building a reliable tens-and-ones structure before regrouping is introduced.",
    whyThisChallenge: "A no-regrouping sum isolates the meaning of each place value.",
    nudge: "Combine the tens first, then the ones.",
    nextMove: "Repeat with a sum that creates ten ones, then trade those ones for one ten.",
    nextMoveWhy: "Prepares the regrouping exchange",
    scaffold: {
      prompt: "Two tens plus one ten makes how many tens?",
      equation: "20 + 10 = ?",
      options: [3, 30, 210],
      answer: 30,
      coach: "Three tens have a value of 30.",
      wrongFeedback: "Count the three long ten-rods by tens: 10, 20, 30.",
      visual: { kind: "base-ten", left: 20, right: 10 },
    },
    celebration: "Seeds counted. You combined each place with its matching place.",
  },
  {
    id: "ration-build",
    eyebrow: "Mission 10 · Ration Lab",
    title: "Find one fair share",
    story: "Twelve snack packs must be shared equally by four rover teams.",
    prompt: "What is 1/4 of 12 snack packs?",
    equation: "¼ of 12 = ?",
    options: [3, 4, 8, 11],
    answer: 3,
    skill: "fractions",
    skillLabel: "Fractions of sets",
    level: 1,
    levelLabel: "Build",
    visual: { kind: "fraction", total: 12, denominator: 4, numerator: 1 },
    insightByAnswer: {
      4: "You named the number of groups instead of the amount in one group.",
      8: "You left one group out rather than finding one fair share.",
      11: "You removed one item instead of making four equal groups.",
    },
    defaultInsight: "The denominator tells how many equal groups to make.",
    learnerRead: "Nova is connecting one fourth with one of four equal groups.",
    whyThisChallenge: "A unit fraction makes the equal-share meaning visible before multiple shares are combined.",
    nudge: "Deal one pack to each team until all 12 are shared.",
    nextMove: "Find two and three of the same shares, then compare their sizes.",
    nextMoveWhy: "Builds from a unit fraction",
    scaffold: {
      prompt: "Share 8 packs equally into 4 groups. How many are in one group?",
      equation: "8 ÷ 4 = ?",
      options: [2, 4, 12],
      answer: 2,
      coach: "Each of the four groups receives 2 packs.",
      wrongFeedback: "Deal the eight packs one at a time across four groups.",
      visual: { kind: "fraction", total: 8, denominator: 4, numerator: 1 },
    },
    celebration: "Rations are fair. You found one of four equal shares.",
  },
  {
    id: "crater-build",
    eyebrow: "Mission 11 · Crater Path",
    title: "Roll back two tens",
    story: "The rover starts at marker 43 and reverses 20 marks.",
    prompt: "Where does the rover land after moving back 20 from 43?",
    equation: "43 − 20 = ?",
    options: [13, 23, 41, 63],
    answer: 23,
    skill: "subtraction",
    skillLabel: "Subtraction across ten",
    level: 1,
    levelLabel: "Build",
    visual: { kind: "number-line", start: 43, subtract: 20 },
    insightByAnswer: {
      13: "You moved back three tens instead of two.",
      41: "You subtracted two ones instead of two tens.",
      63: "You moved forward rather than backward.",
    },
    defaultInsight: "A jump of 20 changes the tens while the ones stay fixed.",
    learnerRead: "Nova can use whole-ten jumps as a stable base for harder subtraction.",
    whyThisChallenge: "A single whole-ten jump isolates direction and place value.",
    nudge: "Keep the 3 ones. Count back two tens: 43, 33, 23.",
    nextMove: "Split a two-digit subtraction into a whole-ten jump and an ones jump.",
    nextMoveWhy: "Prepares crossing-ten decomposition",
    scaffold: {
      prompt: "Start at 43 and jump back 10 once. Where do you land?",
      equation: "43 − 10 = ?",
      options: [33, 42, 53],
      answer: 33,
      coach: "One jump of ten changes 43 to 33; the ones stay 3.",
      wrongFeedback: "Move one full ten backward while keeping the 3 ones.",
      visual: { kind: "number-line", start: 43, subtract: 10 },
    },
    celebration: "Path cleared. You moved by tens without changing the ones.",
  },
  {
    id: "comms-transfer",
    eyebrow: "Mission 12 · Comms Relay",
    title: "Rebuild the hidden rows",
    story: "A dust cloud hides two rows in a seven-row relay panel.",
    prompt: "The panel has 7 rows of 6 relays. How many relays are there in all?",
    equation: "7 × 6 = ?",
    options: [13, 30, 36, 42],
    answer: 42,
    skill: "arrays",
    skillLabel: "Equal groups",
    level: 3,
    levelLabel: "Transfer",
    visual: { kind: "array", rows: 7, columns: 6, fadedRows: 2 },
    insightByAnswer: {
      13: "You added the factors rather than composing seven groups of six.",
      30: "You counted only the five fully visible rows.",
      36: "You rebuilt one hidden row but not both.",
    },
    defaultInsight: "The hidden rows still belong to the complete equal-group structure.",
    learnerRead: "Nova is ready to reconstruct an array when part of the representation is faded.",
    whyThisChallenge: "Fading two rows tests whether Nova can transfer from a picture to the complete multiplicative structure.",
    nudge: "Count the five clear rows, then add one group of six for each hidden row.",
    nextMove: "Ask Nova to draw or describe a different array with the same total.",
    nextMoveWhy: "Tests flexible multiplicative structure",
    scaffold: {
      prompt: "Five visible rows of 6 relays make how many?",
      equation: "5 × 6 = ?",
      options: [11, 30, 36],
      answer: 30,
      coach: "Five groups of six make 30. Two more groups complete the panel.",
      wrongFeedback: "Skip-count the five visible rows: 6, 12, 18, 24, 30.",
      visual: { kind: "array", rows: 5, columns: 6 },
    },
    celebration: "Relay restored. You reconstructed equal groups after support faded.",
  },
  {
    id: "oxygen-transfer",
    eyebrow: "Mission 13 · Oxygen Reserve",
    title: "Audit the reserve tanks",
    story: "Two reserve decks report 48 and 67 oxygen units.",
    prompt: "How many oxygen units are stored across both decks?",
    equation: "48 + 67 = ?",
    options: [105, 115, 125, 4815],
    answer: 115,
    skill: "placeValue",
    skillLabel: "Place value",
    level: 3,
    levelLabel: "Transfer",
    visual: { kind: "base-ten", left: 48, right: 67 },
    insightByAnswer: {
      105: "The regrouped ten was created but not added to the tens total.",
      125: "One extra ten was counted after regrouping.",
      4815: "The places were concatenated rather than combined.",
    },
    defaultInsight: "Fifteen ones must become one new ten and five ones.",
    learnerRead: "Nova is transferring regrouping to a sum that crosses into a new hundred.",
    whyThisChallenge: "The same exchange rule now changes both the tens and hundreds totals.",
    nudge: "Trade 15 ones for one ten and 5 ones, then count every ten.",
    nextMove: "Have Nova explain why the answer has three digits before calculating another sum.",
    nextMoveWhy: "Links magnitude sense to regrouping",
    scaffold: {
      prompt: "Eight ones plus seven ones becomes one ten and how many ones?",
      equation: "8 + 7 = 10 + ?",
      options: [1, 5, 15],
      answer: 5,
      coach: "Fifteen is one full ten with five ones left.",
      wrongFeedback: "Move ten of the fifteen ones into a bundle. Count what remains.",
      visual: { kind: "base-ten", left: 8, right: 7 },
    },
    celebration: "Reserve verified. You regrouped through a new hundred.",
  },
  {
    id: "habitat-transfer",
    eyebrow: "Mission 14 · Habitat Pods",
    title: "Route the warm air",
    story: "Two of three habitat zones need an equal share of 18 heat cells.",
    prompt: "How many heat cells are in 2/3 of 18?",
    equation: "⅔ of 18 = ?",
    options: [6, 9, 12, 27],
    answer: 12,
    skill: "fractions",
    skillLabel: "Fractions of sets",
    level: 3,
    levelLabel: "Transfer",
    visual: { kind: "fraction", total: 18, denominator: 3, numerator: 2 },
    insightByAnswer: {
      6: "You found one third but did not combine two shares.",
      9: "You split the set into two groups instead of three.",
      27: "You added the group size instead of taking two equal groups.",
    },
    defaultInsight: "Find one third first, then compose two of those shares.",
    learnerRead: "Nova is transferring the unit-fraction strategy to a new denominator and set size.",
    whyThisChallenge: "A new context and denominator reveal whether equal-share reasoning transfers.",
    nudge: "Split 18 into three equal zones, then take two zones.",
    nextMove: "Compare two thirds of 18 with three fourths of 16 and explain what stays the same.",
    nextMoveWhy: "Generalizes the unit-fraction strategy",
    scaffold: {
      prompt: "If 18 cells split into 3 equal zones, how many are in one zone?",
      equation: "18 ÷ 3 = ?",
      options: [3, 6, 9],
      answer: 6,
      coach: "One third of 18 is 6. Two thirds is two groups of 6.",
      wrongFeedback: "Deal all 18 cells equally into three groups and count one group.",
      visual: { kind: "fraction", total: 18, denominator: 3, numerator: 1 },
    },
    celebration: "Air routed. You transferred equal-share reasoning to thirds.",
  },
  {
    id: "drill-transfer",
    eyebrow: "Mission 15 · Core Drill",
    title: "Measure the drill return",
    story: "The core drill reached marker 71 and retracted 46 marks.",
    prompt: "At which marker did the drill stop after retracting 46 from 71?",
    equation: "71 − 46 = ?",
    options: [25, 35, 45, 117],
    answer: 25,
    skill: "subtraction",
    skillLabel: "Subtraction across ten",
    level: 3,
    levelLabel: "Transfer",
    visual: { kind: "number-line", start: 71, subtract: 46 },
    insightByAnswer: {
      35: "You subtracted 36 rather than all 46 marks.",
      45: "The tens jump stopped one ten too early.",
      117: "You combined the distances instead of finding what remains.",
    },
    defaultInsight: "Decompose 46 into 40 and 6, then cross the final ten carefully.",
    learnerRead: "Nova is transferring two-step decomposition to a larger range with less visual support.",
    whyThisChallenge: "A longer jump tests whether Nova owns the decomposition strategy beyond the practiced numbers.",
    nudge: "Jump back 40 to 31, then back 6 to 25.",
    nextMove: "Ask Nova to solve the same problem by adding up from 25 to 71 and compare strategies.",
    nextMoveWhy: "Builds strategy flexibility and verification",
    scaffold: {
      prompt: "Start at 71 and jump back 40. Where do you land?",
      equation: "71 − 40 = ?",
      options: [21, 31, 67],
      answer: 31,
      coach: "Four tens backward changes 71 to 31. Six more marks remain.",
      wrongFeedback: "Count back four tens while keeping the ones digit at 1.",
      visual: { kind: "number-line", start: 71, subtract: 40 },
    },
    celebration: "Core secured. You transferred decomposition to a longer subtraction path.",
  },
];
